# Generated by Django 2.1.7 on 2020-01-08 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200108_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 8, 1, 58, 0, 688851)),
        ),
    ]
