# Generated by Django 2.1.7 on 2020-03-30 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200330_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 30, 10, 33, 30, 406128)),
        ),
    ]
